spot:
  binance:  ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "VIRTUAL_USDT"]
  bybit:    ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  kucoin:   ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  okx:      ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "VIRTUAL_USDT"]
  coinbase: ["BTC_USD",  "ETH_USD",  "SPX_USD"]
  mexc:     ["BTC_USDT", "ETH_USDT", "SPX_USDT", "AIXBT_USDT"]

perp:
  binance:     ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  okx:         ["BTC_USDT", "ETH_kSDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  bybit:       ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  kucoin:      ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  bingx:       ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  apex:        ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "SPX_USDT", "VIRTUAL_USDT"]
  hyperliquid: ["BTC_USDC", "ETH_USDC", "AIXBT_USDC", "SPX_USDC", "VIRTUAL_USDC"]
  nado:        ["BTC_USDT", "ETH_USDT",               "SPX_USDT",               ]
  extended:    ["BTC_USD",  "ETH_USD",                "SPX_USD",  "VIRTUAL_USD"]
  apex:        ["BTC_USDT", "ETH_USDT",               "SPX_USDT", "VIRTUAL_USDT"]
  coinbase:    ["BTC_USD", "ETH_USD"]

onchain:
  rpc_env: "BASE_WSS_RPC"
  aerodrome:
    pools:
      - address: "0xb2cc224c1c9feE385f8ad6a55b4d94E92359DC59"
        symbol: "ETH_USDC"
      - address: "0x22A52bB644f855ebD5ca2edB643FF70222D70C31"
        symbol: "AIXBT_ETH"
      - address: "0x3f0296BF652e19bca772EC3dF08b32732F93014A"
        symbol: "VIRTUAL_ETH"
      - address: "0x4BA1e3E9280facbAcaFA7baF4aE0b78Bea60beCa"
        symbol: "SPX_ETH"
      - address: "0x3e66e55e97ce60096f74b7C475e8249f2D31a9fb"
        symbol: "BTC_USDC"
  uniswap:
    pools:
      - address: "0x6c561B446416E1A00E8E93E221854d6eA4171372"
        symbol: "ETH_USDC"
      - address: "0xf1Fdc83c3A336bdbDC9fB06e318B08EadDC82FF4"
        symbol: "AIXBT_USDC"
      - address: "0x9c087Eb773291e50CF6c6a90ef0F4500e349B903"
        symbol: "VIRTUAL_ETH"
      - address: "0xfBB6Eed8e7aa03B138556eeDaF5D271A5E1e43ef"
        symbol: "BTC_USDC"

fair_price:
  model: "kalman"
  sigma_mode: "instant_spread"
  bias_ewma_halflife_s: 3600.0
  spread_ewma_halflife_s: 3.0
  sigma_k_floor: 1e-6
  vol_engine:
    type: "gk_ewma"
    default_init_ann_vol: 1.0
    halflife_s: 600.0
    floor_ann: 0.50
    bar_min: 1
    max_bars: 1440
    BTC:
      init_ann_vol: 0.80
      floor_ann: 0.30
    ETH:
      init_ann_vol: 1.27
      floor_ann: 0.30
    VIRTUAL:
      init_ann_vol: 2.50
      floor_ann: 0.80
    AIXBT:
      init_ann_vol: 3.16
      floor_ann: 1.00
    SPX:
      init_ann_vol: 2.00
      floor_ann: 0.80
