perp:
  binance:     [BTC_USDT, ETH_USDT, SOL_USDT, HYPE_USDT, TAO_USDT, NEAR_USDT, DOGE_USDT]
  risex:       [BTC_USDC, ETH_USDC, SOL_USDC, HYPE_USDC, TAO_USDC, NEAR_USDC, DOGE_USDC]
  bybit:       [BTC_USDT, ETH_USDT, SOL_USDT, HYPE_USDT, TAO_USDT, NEAR_USDT, DOGE_USDT]
  hyperliquid: [BTC_USDC, ETH_USDC, SOL_USDC, HYPE_USDC, TAO_USDC, NEAR_USDC, DOGE_USDC]

trades:
  binance:     [BTC_USDT, ETH_USDT, SOL_USDT, HYPE_USDT, TAO_USDT, NEAR_USDT, DOGE_USDT]
  risex:       [BTC_USDC, ETH_USDC, SOL_USDC, HYPE_USDC, TAO_USDC, NEAR_USDC, DOGE_USDC]
  hyperliquid: [BTC_USDC, ETH_USDC, SOL_USDC, HYPE_USDC, TAO_USDC, NEAR_USDC, DOGE_USDC]
