spot:
  binance:  ["BTC_USDT", "UNI_USDT"]
  coinbase: ["BTC_USD", "ETH_USD", "UNI_USD"]
  kraken:   ["BTC_USD", "ETH_USD", "AIXBT_USD"]
  mexc:    ["BTC_USDT", "ETH_USDT", "AIXBT_USDT"]
  bybit:   ["BTC_USDT", "ETH_USDT", "AIXBT_USDT", "VIRTUAL_USDT"]

perp:
  binance:  ['BTC_USDT', "ETH_USDT", 'AIXBT_USDT', 'UNI_USDT']
  coinbase: ['BTC_USD', 'ETH_USD']
  kraken:   ['BTC_USD', 'ETH_USD']
  bybit:    ['BTC_USDT', "UNI_USDT"]
  lighter:  ['BTC_USDC', "UNI_USDC"]
  extended: ['BTC_USD', 'ETH_USD', 'UNI_USD']
  nado:     ['BTC_USDT', 'ETH_USDT', 'UNI_USDT']
