tau: 0.1
relative: true
fit_timestamp: '2026-03-07T02:27:10Z'
models:
  AIXBT:
    venues:
    - bybit|PERP-AIXBT-USDT
    - okx|SPOT-AIXBT-USDT
    - okx|PERP-AIXBT-USDT
    - binance|PERP-AIXBT-USDT
    - bingx|PERP-AIXBT-USDT
    - kucoin|PERP-AIXBT-USDT
    fresh_shares:
    - 0.36317
    - 0.026851
    - 7.5e-05
    - 0.609389
    - 6.5e-05
    - 0.000451
    betas:
    - 0.0
    - 0.0
    - 0.0
    - 3.0
    - 20.0
    - 0.0
  BTC:
    venues:
    - coinbase|SPOT-BTC-USD
    - coinbase|PERP-BTC-USD
    - binance|PERP-BTC-USDT
    - kraken|PERP-BTC-USD
    - bybit|PERP-BTC-USDT
    - okx|SPOT-BTC-USDT
    - okx|PERP-BTC-USDT
    - bingx|PERP-BTC-USDT
    - kucoin|PERP-BTC-USDT
    - apex|PERP-BTC-USDT
    fresh_shares:
    - 0.887907
    - 0.007066
    - 0.071328
    - 0.000232
    - 5.0e-06
    - 0.019329
    - 0.01084
    - 0.000134
    - 0.002848
    - 0.000311
    betas:
    - 0.0
    - 2.090325
    - 0.0
    - 0.067496
    - 24.89228
    - 0.084796
    - 0.07552
    - 0.0
    - 0.0
    - 0.0
  CLANKER:
    venues:
    - coinbase|SPOT-CLANKER-USD
    - coinbase|PERP-CLANKER-USD
    - bybit|PERP-CLANKER-USDT
    - kraken|SPOT-CLANKER-USD
    - binance|PERP-CLANKER-USDT
    - bingx|PERP-CLANKER-USDT
    - kucoin|PERP-CLANKER-USDT
    fresh_shares:
    - 0.999604
    - 0.000142
    - 0.00019
    - 1.0e-06
    - 1.5e-05
    - 5.0e-06
    - 4.3e-05
    betas:
    - 0.0
    - 0.99426
    - 0.0
    - 0.638894
    - 0.0
    - 3.878311
    - 0.543235
  ETH:
    venues:
    - coinbase|SPOT-ETH-USD
    - coinbase|PERP-ETH-USD
    - binance|PERP-ETH-USDT
    - kraken|PERP-ETH-USD
    - bybit|PERP-ETH-USDT
    - okx|SPOT-ETH-USDT
    - okx|PERP-ETH-USDT
    - kraken|SPOT-ETH-USD
    - bingx|PERP-ETH-USDT
    - kucoin|PERP-ETH-USDT
    fresh_shares:
    - 0.875487
    - 0.007241
    - 0.092542
    - 0.000119
    - 0.015226
    - 0.000745
    - 0.007353
    - 0.000477
    - 0.000811
    - 0.0
    betas:
    - 0.0
    - 5.061034
    - 0.0
    - 0.282347
    - 0.0
    - 0.075679
    - 18.978172
    - 0.122883
    - 0.0
    - 0.0
  KAITO:
    venues:
    - coinbase|PERP-KAITO-USD
    - coinbase|SPOT-KAITO-USD
    - apex|PERP-KAITO-USDT
    - bingx|PERP-KAITO-USDT
    - binance|PERP-KAITO-USDT
    fresh_shares:
    - 0.994714
    - 0.000714
    - 0.000109
    - 0.000414
    - 0.004048
    betas:
    - 1.0
    - 0.0
    - 0.0
    - 0.1
    - 0.0
  SPX:
    venues:
    - coinbase|SPOT-SPX-USD
    - coinbase|PERP-SPX-USD
    - binance|PERP-SPX-USDT
    - bybit|PERP-SPX-USDT
    - okx|PERP-SPX-USDT
    - kraken|SPOT-SPX-USD
    - bingx|PERP-SPX-USDT
    - kucoin|PERP-SPX-USDT
    - apex|PERP-SPX-USDT
    fresh_shares:
    - 0.978708
    - 0.000185
    - 0.012806
    - 0.001105
    - 8.0e-06
    - 0.003415
    - 0.000708
    - 0.003058
    - 6.0e-06
    betas:
    - 0.0
    - 0.0
    - 0.0
    - 20.0
    - 0.0
    - 0.0
    - 20.0
    - 0.0
    - 0.0
